---
version: "3.7"

services:

  php:
    image: nanoninja/php-fpm:7.2
    working_dir: /php
    volumes:
    - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    - ./php:/php

  nginx:
    image: nginx:1.15.5
    ports:
    - 80:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./nginx/public:/var/www/html/public:ro

  sql:
    image: mariadb:10.3.8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wcf
    volumes:
    - ./dumps/dump.sql:/docker-entrypoint-initdb.d/00000_init.sql
    ports:
    - 3316:3306

